#!/usr/bin/env node
/**
 * Generate src/types/supabase.ts from a live Postgres — the same generator the
 * Supabase CLI runs, but without needing Docker.
 *
 *   DATABASE_URL=postgresql://... npm run gen:types
 *
 * Equivalent to: supabase gen types typescript --db-url "$DATABASE_URL" --schema public
 * Run it after every migration and commit the result. Never hand-edit the output.
 */
import { writeFileSync } from 'node:fs';
import { PostgresMeta } from '@supabase/postgres-meta';
import { getGeneratorMetadata } from '@supabase/postgres-meta/dist/lib/generators.js';
import { generateTypescript } from '@supabase/postgrest-typegen';

const url = process.env.DATABASE_URL;
if (!url) {
  console.error('DATABASE_URL is not set');
  process.exit(1);
}

const pgMeta = new PostgresMeta({ connectionString: url, max: 1 });
try {
  const { data, error } = await getGeneratorMetadata(pgMeta, { includedSchemas: ['public'], excludedSchemas: [] });
  if (error) throw error;
  const out = await generateTypescript(data, { detectOneToOneRelationships: false, defaultSchema: 'public' });
  const header = '// GENERATED by scripts/gen-types.mjs — do not edit. Regenerate after every migration.\n';
  writeFileSync(new URL('../src/types/supabase.ts', import.meta.url), header + out);
  console.log('wrote src/types/supabase.ts');
} finally {
  await pgMeta.end();
}
